# Generated by Django 3.1.4 on 2020-12-11 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('house_id', models.IntegerField(primary_key=True, serialize=False)),
                ('house_name', models.CharField(max_length=64, unique=True)),
                ('city', models.CharField(max_length=32)),
                ('address', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('created_date', models.DateField(auto_now=True)),
                ('status_code', models.IntegerField()),
            ],
            options={
                'db_table': 'house',
            },
        ),
    ]
