# Generated by Django 3.1.4 on 2020-12-11 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_house'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_ucode', models.CharField(max_length=64, unique=True)),
                ('sensor_name', models.CharField(max_length=64, unique=True)),
                ('unit', models.CharField(max_length=32)),
                ('precision_percent', models.FloatField()),
                ('min_value', models.FloatField()),
                ('max_value', models.FloatField()),
                ('maker', models.CharField(max_length=64)),
                ('model_code', models.CharField(max_length=64)),
                ('status_code', models.IntegerField()),
                ('used_date', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'sensor',
            },
        ),
        migrations.CreateModel(
            name='SensorType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'sensortype',
            },
        ),
        migrations.CreateModel(
            name='Thing',
            fields=[
                ('thing_id', models.IntegerField(primary_key=True, serialize=False)),
                ('coordinate_x', models.FloatField()),
                ('coordinate_y', models.FloatField()),
                ('cpu_temp', models.FloatField()),
                ('fan_flag', models.BooleanField(default=True)),
                ('status_code', models.IntegerField()),
                ('created_date', models.DateField(auto_now=True)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.house')),
            ],
            options={
                'db_table': 'thing',
            },
        ),
        migrations.CreateModel(
            name='SensorValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_value', models.FloatField()),
                ('unit', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sensor')),
            ],
            options={
                'db_table': 'sensorvalue',
            },
        ),
        migrations.AddField(
            model_name='sensor',
            name='sensor_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sensortype'),
        ),
        migrations.AddField(
            model_name='sensor',
            name='thing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.thing'),
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('machine_id', models.IntegerField(primary_key=True, serialize=False)),
                ('machine_name', models.CharField(max_length=64, unique=True)),
                ('maker', models.CharField(max_length=64)),
                ('model_code', models.CharField(max_length=64)),
                ('ele_consumption', models.FloatField()),
                ('coordinate_x', models.FloatField()),
                ('coordinate_y', models.FloatField()),
                ('status_code', models.IntegerField()),
                ('created_date', models.DateField(auto_now=True)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.house')),
            ],
            options={
                'db_table': 'machine',
            },
        ),
    ]
