# Generated by Django 3.1.4 on 2020-12-16 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20201216_0711'),
    ]

    operations = [
        migrations.RenameField(
            model_name='machine',
            old_name='coordinate_x',
            new_name='position_x',
        ),
        migrations.RenameField(
            model_name='machine',
            old_name='coordinate_y',
            new_name='position_y',
        ),
        migrations.AlterField(
            model_name='machine',
            name='status_code',
            field=models.IntegerField(choices=[(1, 'working'), (2, 'standby'), (3, 'malfunction')]),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='status_code',
            field=models.IntegerField(choices=[(1, 'working'), (2, 'standby'), (3, 'malfunction')]),
        ),
    ]
