# Generated by Django 3.0.5 on 2020-05-19 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='img_path',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
